# MicroGrid




## MicroGrid System Overview



![](new_design.png)

Advantages of this multi-agent design with autogen:
- Collaborative Problem Solving: The collaboration among the user proxy agent and the assistant agents fosters a cooperative problem-solving environment. The agents can share information and knowledge, allowing them to complement each other's abilities and collectively arrive at better solutions. On the other hand, the Safeguard acts as a virtual adversarial checker, which can perform another safety check pass on the generated code.

- Modularity: The division of tasks into separate agents promotes modularity in the system. Each agent can be developed, tested, and maintained independently, simplifying the overall development process and facilitating code management.

- Memory Management: The UnbiasedCathode agent's role in maintaining memory related to user interactions is crucial. The memory retention allows the agents to have context about a user's prior questions, making the decision-making process more informed and context-aware.



In [1]:
# Install Required Packages
%pip install optiguide
%pip install rsome
%pip install --force-reinstall -v "openai==0.28.1"

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Using pip 21.2.4 from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)
Defaulting to user installation because normal site-packages is not writeable
  Using cached openai-0.28.1-py3-none-any.whl (76 kB)
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
  Using cached aiohttp-3.9.1-cp39-cp39-macosx_11_0_arm64.wh

In [2]:
# test Gurobi installation
import gurobipy as gp
from gurobipy import GRB
from eventlet.timeout import Timeout

# import auxillary packages
import requests  # for loading the example source code
import openai

# import flaml and autogen
from flaml import autogen
from flaml.autogen.agentchat import Agent, UserProxyAgent
import json

/Users/cchaabani/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [3]:
with open("api_keys.json", "r") as keyfile:
    api_key = json.load(keyfile)

print(api_key)
autogen.oai.ChatCompletion.start_logging()
config_list = autogen.config_list_from_json(
    "OAI_CONFIG_LIST",
    filter_dict={
        "model": {
            'gpt-3.5-turbo'
        }
    }
)

config_list = [
    {
        'model': 'gpt-3.5-turbo-16k-0613',
        'api_key': api_key['api_key']
    }]

{'api_key': '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'}


Now, let's import the source code (loading from URL) and also some training examples (defined as string blow).

In [4]:
# Get the source code of materials example
code_url = "../benchmark/application/microgrid.py"
code = open(code_url, "r").read() # for local files

# DEBUG
# show the first head and tail of the source code
print("\n".join(code.split("\n")[:10]))
print(".\n" * 3)
print("\n".join(code.split("\n")[-10:]))

from rsome import ro                # import the ro modeling tool
import numpy as np

###DEFINE ALL PARAMETERS
m= 3 #5 timesteps
n= 4 #6 prosumers
Pprod = np.array([[65,45,36,25],
                      [60, 40,30,27],
                       [69,44,31,26]]
                      )
.
.
.

print("############")
print("objective value:",obj_value)
print("Import:",Pimport )
print("Export:",Pexport )
    
print("Charge Battery:",Bcharge )
print("Discharge Battery:",Bdischarge )
print("SoE:",Soe )
print("SoEnext:",soenext )



In [5]:
# In-context learning examples.
from tools import *

icl_db = "../benchmark/application/Dataset/questions_db.csv"
example_qa_code = icl_code_generator(icl_db)
example_qa_interpreter = icl_interpreter(icl_db)

print(example_qa_code)

At the timestep 2 if the community's load doubles, what would be the profit?
Answer Code:
python for load in range(Pcons[2]):	Pcons[2][load] = 2*Pcons[2][load]
If the community's load triples, how much I get profit?
Answer Code:
python Pcons = Pcons*3
What should be the state of energy of the battery if the community's load consumption is reduced to half?
Answer Code:
python Pcons = Pcons/2
What would be the profit if the community exports are smaller than this amount of power [10,30,20] to the grid?
Answer Code:
python model.st(Pexp<=np.array([10,30,20]))
What would be the profit if the community imports are smaller than this amount of power [10,30,20] from the grid?
Answer Code:
python model.st(Pimp<=np.array([10,30,20]))

Answer Code:
python model.st((PriceImp*Pimp).sum() - (PriceEx * Pexp).sum() == 0)



Now, let's create an Unbiased Cathode agent and also a user.

For the Unbiased Cathode agent, we only allow "debug_times" to be 1, which means it can debug its answer once if it encountered errors.

In [6]:
import sys
sys.path.append("../")
from SGPChat.unbiasedcathode import UnbiasedCathodeAgent

agent = UnbiasedCathodeAgent(
    name="Unbiased Cathode Grid Example",
    source_code=code,
    debug_times=1,
    example_qa_coder=example_qa_code,
    example_qa_interpreter="",
    llm_config={
        "request_timeout": 600,
        "seed": 42,
        "config_list": config_list,
    }
)

user = UserProxyAgent(
    "user", max_consecutive_auto_reply=0,
    human_input_mode="NEVER", code_execution_config=False
)

SOLVING
Being solved by the default MILP solver...
Solution status: 0
Running time: 0.0105s
PV Production [[65 45 36 25]
 [60 40 30 27]
 [69 44 31 26]]
Load [[10 30 20 25]
 [13 24 20 25]
 [25 26 20 25]]
############
objective value: -26.111111111111114
Import: [0. 0. 0.]
Export: [94.7037037 83.7037037 82.7037037]
Charge Battery: [[ 3.14814815  0.         -0.          0.92592593]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
Discharge Battery: [[-0.          8.88888889  3.88888889  0.        ]
 [ 8.7037037   0.          0.          0.        ]
 [ 0.          0.          0.          8.7037037 ]]
SoE: [[2800.         3400.         2500.         3200.        ]
 [3366.66666667 1800.         1800.         3366.66666667]
 [1800.         1800.         1800.         3366.66666667]]
SoEnext: [[3366.66666667 1800.         1800.         3366.66666667]
 [1800.         1800.         1800.         3366.66666667]
 [1800.         1800.         18

Now, let's create a user's question.

In [7]:
user.initiate_chat(agent, message="At the timestep 2 if the community's load doubles, what would be the profit?")

user (to Unbiased Cathode Grid Example):

At the timestep 2 if the community's load doubles, what would be the profit?

--------------------------------------------------------------------------------
Unbiased Cathode Grid Example (to writer):


Answer Code:


--------------------------------------------------------------------------------
writer (to Unbiased Cathode Grid Example):

To calculate the profit at timestep 2 when the community's load doubles, you need to update the `Pcons` array. Here is the code snippet:

```python
for load in range(len(Pcons[2])):
    Pcons[2][load] *= 2
```

This code will double the load values at timestep 2. After updating the load values, you can run the solver to calculate the new profit.

--------------------------------------------------------------------------------
Unbiased Cathode Grid Example (to safeguard):


--- Code ---
for load in range(len(Pcons[2])):
    Pcons[2][load] *= 2

--- One-Word Answer: SAFE or DANGER ---


----------------------

In [8]:
user.initiate_chat(agent, message="What is the material usage if the quality threshold increases by 10%?")

user (to Unbiased Cathode Grid Example):

What is the material usage if the quality threshold increases by 10%?

--------------------------------------------------------------------------------
Unbiased Cathode Grid Example (to writer):


Answer Code:


--------------------------------------------------------------------------------
writer (to Unbiased Cathode Grid Example):

As per your question, if the quality threshold increases by 10%, the material usage can be calculated by multiplying the original material usage by 1.1. 

Here is the code snippet for your reference:

```python
# Multiply the material usage by 1.1
material_usage = material_usage * 1.1
```

Please replace `material_usage` with the actual variable name in your code.

--------------------------------------------------------------------------------
Unbiased Cathode Grid Example (to safeguard):


--- Code ---
# Multiply the material usage by 1.1
material_usage = material_usage * 1.1

--- One-Word Answer: SAFE or DANGER

In [9]:
'''
Problems: Agent Writer does not seem to be able to interpret the results of the optimization correctly. 
Approach: Try in-context learning there as well 

'''

'\nProblems: Agent Writer does not seem to be able to interpret the results of the optimization correctly. \nApproach: Try in-context learning there as well \n\n'